name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image:latest

    - name: Run the Docker container
      run: docker run --name build-container my-image:latest

    - name: Copy PDF from container
      run: docker cp build-container:/app/. ./output/

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: specification-pdf
        path: output/*.pdf
